### ISSUE TITLE
servo.get_positions() read positions but servo isn't connected

### ISSUE THREAD

**Issue by jingxiangmo** [Zeroth-Robotics/OpenLCH#26]
<img width="631" alt="image" src="https://github.com/user-attachments/assets/b599f877-eb36-4d9d-97c7-319ae570f065">

clear cache?

lol

**Comment by hatomist** [comment]
partially by design, the read multiple servos command reads the memory chunk that has the latest values for the servos. We have a scan command to figure out if some of the servos are offline;
not sure what's the better path here for error handling. In ideal world all of the servos are connected and we feed data to the inference engine/classical control, right now if a servo gets disconnected it will report last known position. we need to decide if that's the best way to error handle or not (if a servo is disconnected/malfunctioning do we want to continue executing policy or panic)

**Comment by jingxiangmo** [comment]
yeah, i think we need to have testing initializing scripts to figure out if the servos are connected etc (error handling)
